variables:
  DEBUG: "1"

.test_job:
  image: debian:stable
  tags:
    - docker
  artifacts:
    expire_in: 1 day
    paths:
      - sources
  before_script:
    - apt update -y && apt -y upgrade && apt install -y git mmdebstrap in-toto python3-pip python3-requests
      python3-apt python3-debian python3-dateutil python3-setuptools python3-rstr python3-httpx python3-tenacity
      diffoscope debian-keyring debian-archive-keyring debian-ports-archive-keyring
      python3-requests-mock python3-pytest python3-pytest-mock python3-pytest-cov
    - pip3 install -U python-debian

tests:
  extends: .test_job
  script: PYTHONPATH=. pytest-3 -v --log-cli-level=DEBUG
    --cov app --cov-report term --cov-report html:artifacts/htmlcov --cov-report xml:artifacts/coverage.xml
    --junitxml=artifacts/app.xml tests/test_*.py
