variables:
  DEBUG: "1"

.test_job:
  image: docker/compose:latest
  services:
    - docker:dind
  tags:
    - docker

tests:
  extends: .test_job
  artifacts:
    paths:
      - artifacts/htmlcov/
    reports:
      junit: artifacts/app.xml
      cobertura: artifacts/coverage.xml
  coverage: '/TOTAL.*\s(\d+)%/'
  script:
    - docker-compose -f tests/docker-compose.yml build base test
    - docker-compose -f tests/docker-compose.yml run test
