version: '3'

services:

### rebuilder_base

  base:
    image: rebuilder_base
    build:
      context: .
      dockerfile: Dockerfile

### Celery

  broker:
    restart: always
    image: 'docker.io/redis'
    ports:
     - '6379:6379'

  beat:
    restart: always
    image: 'rebuilder_base'
    volumes:
      - .:/app
    depends_on:
      - broker
    links:
      - broker
    environment:
      - CELERY_BROKER_URL=redis://broker:6379/0
      - CELERY_BACKEND_URL=db+sqlite:////db/results.sqlite
# https://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html?highlight=periodic#starting-the-scheduler
    entrypoint: celery -A app worker -B -s /tmp/celerybeat-schedule --loglevel=INFO

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://broker:6379/0
      - CELERY_BACKEND_URL=db+sqlite:////db/results.sqlite
      - FLOWER_PORT=5556
    ports:
      - 5556:5556

### PackageRebuilder

  getter:
    restart: always
    image: 'rebuilder_base'
    volumes:
      - .:/app
# getter worker needs to store results in backend (here a sqlite file)
      - '/var/lib/rebuilder/db:/db'
    depends_on:
      - broker
    links:
      - broker
    environment:
      - CELERY_BROKER_URL=redis://broker:6379/0
      - CELERY_BACKEND_URL=db+sqlite:////db/results.sqlite
# https://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html?highlight=periodic#starting-the-scheduler
    entrypoint: celery -A app worker --loglevel=INFO -O fair --prefetch-multiplier 1 -c 1 --queues=get

  rebuilder:
    restart: always
    privileged: true
    build:
      context: .
      dockerfile: rebuilder.Dockerfile
    volumes:
      - .:/app
# rebuilder worker needs to store results in backend (here a sqlite file)
      - '/var/lib/rebuilder/db:/db'
# rebuilder worker needs artifacts directory and GPG for signing in-toto metadata
      - '/var/lib/rebuilder/rebuild:/rebuild'
      - '/var/lib/rebuilder/gnupg:/root/.gnupg'
    depends_on:
      - broker
    links:
      - broker
    environment:
      - CELERY_BROKER_URL=redis://broker:6379/0
      - CELERY_BACKEND_URL=db+sqlite:////db/results.sqlite
# https://docs.celeryproject.org/en/stable/reference/cli.html#cmdoption-celery-worker-c
    entrypoint: celery -A app worker --loglevel=INFO  -O fair --prefetch-multiplier 1 -c 1 --queues=rebuild
# This is for specifing the number of rebuilder worker. Alternatively, you can use: docker-compose scale rebuilder=X
#    deploy:
#      mode: replicated
#      replicas: 2

  uploader:
    restart: always
    image: 'rebuilder_base'
    volumes:
      - .:/app
# uploader worker needs to store results in backend (here a sqlite file)
      - '/var/lib/rebuilder/db:/db'
# uploader worker needs artifacts directory and SSH key for rsyncing on remote location
      - '/var/lib/rebuilder/rebuild:/rebuild'
      - '/var/lib/rebuilder/ssh:/root/.ssh'
    depends_on:
      - broker
    links:
      - broker
    environment:
      - CELERY_BROKER_URL=redis://broker:6379/0
      - CELERY_BACKEND_URL=db+sqlite:////db/results.sqlite
    entrypoint: celery -A app worker --loglevel=INFO -O fair --prefetch-multiplier 1 -c 1 --queues=upload

  state:
    restart: always
    image: 'rebuilder_base'
    volumes:
      - .:/app
      - '/var/lib/rebuilder/rebuild:/rebuild'
    depends_on:
      - broker
    links:
      - broker
    environment:
      - CELERY_BROKER_URL=redis://broker:6379/0
      - CELERY_BACKEND_URL=db+sqlite:///db/results.sqlite
    entrypoint: celery -A app worker --loglevel=INFO -O fair --prefetch-multiplier 1 -c 1 --queues=state
